### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by bioluria** [hillerlab/make_lastz_chains#62]
I tested make _lastz _chains with the mouse genome mm10 and the human genome hg19, running the script as follows:
`python3 /home/luria/make_lastz_chains-2.0.8/make_chains.py hg19 mm10 /home/luria/hg19_chrom.fa /home/luria/mm10_chrom.fa --project_dir /home/luria/mm10_vs_hg19`

But I got the following error：
fatal: Not a git repository (or any parent up to mount point /work)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
# Make Lastz Chains #
Version 2.0.8
Commit: unknown
Branch: unknown

* found run_lastz.py at /home/luria/make_lastz_chains-2.0.8/standalone_scripts/run_lastz.py
* found run_lastz_intermediate_layer.py at /home/luria/make_lastz_chains-2.0.8/standalone_scripts/run_lastz_intermediate_layer.py
* found chain_gap_filler.py at /home/luria/make_lastz_chains-2.0.8/standalone_scripts/chain_gap_filler.py
* found faToTwoBit at /home/luria/software/UCSCTOOLS/faToTwoBit
* found twoBitToFa at /home/luria/software/UCSCTOOLS/twoBitToFa
* found pslSortAcc at /home/luria/make_lastz_chains-2.0.8/HL_kent_binaries/pslSortAcc
* found axtChain at /home/luria/software/UCSCTOOLS/axtChain
* found axtToPsl at /home/luria/software/UCSCTOOLS/axtToPsl
* found chainAntiRepeat at /home/luria/software/UCSCTOOLS/chainAntiRepeat
* found chainMergeSort at /home/luria/software/UCSCTOOLS/chainMergeSort
* found chainCleaner at /home/luria/make_lastz_chains-2.0.8/HL_kent_binaries/chainCleaner
* found chainSort at /home/luria/software/UCSCTOOLS/chainSort
* found chainScore at /home/luria/software/UCSCTOOLS/chainScore
* found chainNet at /home/luria/software/UCSCTOOLS/chainNet
* found chainFilter at /home/luria/software/UCSCTOOLS/chainFilter
* found lastz at /home/luria/software/lastz/lastz-1.04.22/src/lastz
* found nextflow at /home/luria/software/nextflow/nextflow
All necessary executables found.
Making chains for /home/luria/hg19_chrom.fa and /home/luria/mm10_chrom.fa files, saving results to /home/luria/mm10_vs_hg19
Pipeline started at 2024-06-14 10:42:39.138852
* Setting up genome sequences for target
genomeID: hg19
input sequence file: /home/luria/hg19_chrom.fa
is 2bit: False
planned genome dir location: /home/luria/mm10_vs_hg19/target.2bit
Initial fasta file /home/luria/hg19_chrom.fa saved to /home/luria/mm10_vs_hg19/target.2bit
For hg19 (target) sequence file: /home/luria/mm10_vs_hg19/target.2bit; chrom sizes saved to: /home/luria/mm10_vs_hg19/target.chrom.sizes
* Setting up genome sequences for query
genomeID: mm10
input sequence file: /home/luria/mm10_chrom.fa
is 2bit: False
planned genome dir location: /home/luria/mm10_vs_hg19/query.2bit
Initial fasta file /home/luria/mm10_chrom.fa saved to /home/luria/mm10_vs_hg19/query.2bit
For mm10 (query) sequence file: /home/luria/mm10_vs_hg19/query.2bit; chrom sizes saved to: /home/luria/mm10_vs_hg19/query.chrom.sizes

### Partition Step ###

# Partitioning for target
Saving partitions and creating 26 buckets for lastz output
In particular, 23 partitions for bigger chromosomes
And 3 buckets for smaller scaffolds
Saving target partitions to: /home/luria/mm10_vs_hg19/target_partitions.txt
# Partitioning for query
An error occurred while executing partition: 'bool' object is not iterable
Traceback (most recent call last):
  File "/home/luria/make_lastz_chains-2.0.8/modules/step_manager.py", line 70, in execute_steps
    step_result = step_to_function[step](params, project_paths, step_executables)
  File "/home/luria/make_lastz_chains-2.0.8/modules/pipeline_steps.py", line 43, in partition_step
    executables)
  File "/home/luria/make_lastz_chains-2.0.8/steps_implementations/partition.py", line 80, in do_partition_for_genome
    bulk_num_to_chroms = create_buckets_for_little_scaffolds(little_scaffolds_to_bulk, chunk_size)
  File "/home/luria/make_lastz_chains-2.0.8/steps_implementations/partition.py", line 41, in create_buckets_for_little_scaffolds
    for chrom, size in little_scaffolds_to_bulk or chrom_count_in_bulk >= Constants.MAX_CHROM_IN_BULK:
TypeError: 'bool' object is not iterable

**Comment by jurin0811** [comment]
Hello, I have the same problem, did you solve it? Maybe using this should also want to use TOGA to do gene conversion, do you have any good software recommendation？Thank you ！

**Comment by alejandrogzi** [comment]
Hi both,

This has must be covered and solved in https://github.com/hillerlab/make_lastz_chains/pull/109 and https://github.com/hillerlab/make_lastz_chains/pull/115 for any version >= 3.0.0. Thanks for reporting!
